server:
  port: 8888
spring:
  datasource:
    username: hsj
    password: 123#123
    url: jdbc:oracle:thin:url:port:database
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
