#server:
#  port: 8888
#
#
#spring:
#  thymeleaf:
#    cache: false
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    date-format: yyyy-MM-dd
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles:
    active: mysql
#    active: oracle
logging:
  level:
    com.hsj: debug
    root: info
